# Generated by Django 5.0.1 on 2025-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('home', 'Home & Furniture'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
